dist: focal

language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - cd examples/
  - mkdir data
  - python run_bennett_2021.py
  - python plot_data.py --stats --only-nids --verbose
  - python plot_model.py --only-nids --values --weights
  - python create_arena_paths.py --nb-flies 3 --nb-time-steps 100 -R 10 --dir data
  - python plot_arena_fishbone.py -R 10 --dir data
  - python plot_arena_fishbone_weights.py -R 10 --dir data
  - python run_unpaired_a.py
  - python run_handler_2019.py