dist: focal

language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - cd examples/
  - python test_learning_rule.py
  - python run_subcircuits.py --nb-kc 10 --sm --rm --ltm --rrm --rfm --mam
  - python run_incentive_circuit.py --nb-kc 10 --only-nids --structure
  - python run_incentive_circuit.py --nb-kc 10 --only-nids --values --weights
  - python run_incentive_wheel.py --nb-kc 10 --only-nids --structure
  - python run_incentive_wheel.py --nb-kc 10 --only-nids --values --weights
  - python run_data_analysis.py --stats --only-nids --verbose
  - python create_paths.py --nb-flies 100 --nb-time-steps 100
  - python run_arena_paths.py
  - python run_arena_stats.py
  - python run_olfactory_conditioning.py
  - python run_bennet_2021.py