dist: focal

language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - cd examples/
  - mkdir data
  - python test_learning_rule.py
  - python run_microcircuits.py --nb-kc 10 --sm --rm --ltm --rrm --rfm --mam
#  - python run_incentive_circuit.py --nb-kc 10 --only-nids --structure
  - python run_incentive_circuit.py --nb-kc 10 --only-nids --values --weights
  - python run_incentive_wheel.py --nb-kc 10 --only-nids --values --weights
  - python run_data_analysis.py --stats --only-nids --verbose
  - python create_arena_paths.py --nb-flies 10 --nb-time-steps 100 -R 1 --dir data
  - python run_arena_pi.py -R 1 --dir data
  - python run_olfactory_conditioning.py -R 1
  - python run_bennett_2021.py