[build-system]
requires = [
    "setuptools>=40.8.0",
    "wheel",
    "numpy>=1.18.5",
    "scipy",
    "pandas",
    "matplotlib",
    "pyyaml",
    "openpyxl"
]
build-backed = "setuptools.build_meta"